from .storage.ddl import DDLStorage
from .storage.dropbox import DropboxStorage
from .storage.git import GitStorage
from .storage.gitea import GiteaStorage
from .storage.github import GithubStorage
from .storage.gitlab import GitlabStorage
from .storage.internetarchive import InternetArchiveStorage
from .storage.karaokemugen import KaraokeMugenStorage
from .storage.kemono import KemonoStorage
from .storage.local import LocalStorage
from .storage.minio import MinIOStorage
from .storage.myrient import MyrientStorage
from .storage.s3 import S3Storage
from .storage.sftp import SFTPStorage
from .storage.steam import SteamStorage
from .storage.tar import TarStorage
from .storage.tcgdex import TCGDexStorage
from .storage.webdav import WebDAVStorage
from .storage.zip import ZipStorage
from .utils import File, Readable, Writable
