from .storage.alist import AListStorage as AListStorage
from .storage.ddl import DDLStorage as DDLStorage
from .storage.dropbox import DropboxStorage as DropboxStorage
from .storage.git import GitStorage as GitStorage
from .storage.gitea import GiteaStorage as GiteaStorage
from .storage.github import GithubStorage as GithubStorage
from .storage.gitlab import GitlabStorage as GitlabStorage
from .storage.internetarchive import InternetArchiveStorage as InternetArchiveStorage
from .storage.karaokemugen import KaraokeMugenStorage as KaraokeMugenStorage
from .storage.kemono import KemonoStorage as KemonoStorage
from .storage.lexaloffle import LexaloffleStorage as LexaloffleStorage
from .storage.local import LocalStorage as LocalStorage
from .storage.minio import MinIOStorage as MinIOStorage
from .storage.myrient import MyrientStorage as MyrientStorage
from .storage.pokemontcgimages import PokemonTCGImagesStorage as PokemonTCGImagesStorage
from .storage.romm import RomMStorage as RomMStorage
from .storage.s3 import S3Storage as S3Storage
from .storage.sftp import SFTPStorage as SFTPStorage
from .storage.tar import TarStorage as TarStorage
from .storage.tcgdexassets import TCGDexAssetsStorage as TCGDexAssetsStorage
from .storage.webdav import WebDAVStorage as WebDAVStorage
from .storage.zip import ZipStorage as ZipStorage
